name: credo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.10.4'
      - name: Cache mix deps
        uses: actions/cache@v2
        with:
          path: 'deps'
          key: ${{ runner.os }}-mix-deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-deps-
            ${{ runner.os }}-
      - run: mix deps.get
      - run: mix credo
