name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/a/61721608/1993020
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: microlog_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23'
          elixir-version: '1.10.4'
      - name: Cache mix deps
        uses: actions/cache@v2
        with:
          path: 'deps'
          key: ${{ runner.os }}-mix-deps-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-deps-
            ${{ runner.os }}-
      - run: mix deps.get
      - run: mix test
